### ISSUE TITLE
Guideline format

### ISSUE THREAD

**Issue by jgriss** [jgriss/GuidelinesChecklistGenerator#2]
A core idea of the application is to load read guidelines from specially prepared files in order to dynamically create new interactive checklists. This issue focuses on what format to use to specify guidelines.

Again, please +1 suggestions you are in favor for.

**Comment by jgriss** [comment]
# YAML + JSON schema

Use YAML formatted files to store guidelines. The format for these YAML files can be recorded using [JSON schema](http://json-schema.org/) which can then also be used to validate the files.

## Advantage

YAML is comparably easy to read for humans, light-weight and supported by virtually all programming languages.

**Comment by bittremieux** [comment]
# JSON-only

I want to suggest a JSON-only format.

## Advantages

- Better support in most programming languages than YAML. For example, JSON is built into the standard Python library while YAML requires an external package.
- JSON is the standard for exchanging data on the web.

## Disadvantages

- Slightly less human-readable than YAML. On the other hand, the guideline specification documents should be relatively static, so this isn't such a big issue.

**Comment by jgriss** [comment]
@bittremieux Possibly, we could even combine both approaches. Internally build everything around JSON. If we have collaborators from the outside that want to contribute specifications (...) then we could also accept YAML documents that we convert. Since YAML and JSON are fully compatible, this wouldn't be an issue. Does that sound OK?

**Comment by bittremieux** [comment]
That could be an option, although I think the better choice would be to commit to a single format, whether that's JSON or YAML (or something else still). Otherwise you have to maintain two different formats in parallel, which is more work and which could easily lead to technical debt.

**Comment by jgriss** [comment]
This is now a markdown document at https://github.com/eubic/ReproducibleMSGuidelines
