### ISSUE TITLE
Guideline specification items

### ISSUE THREAD

**Issue by jgriss** [jgriss/GuidelinesChecklistGenerator#4]
This issue is focused on what features of a guidelines should be stored. This relates to #2 in the sense that the format chosen in #2 will be used to store this information.

The collection of items in this issue should be kept agnostic of the underlying format used to store them.

Essentially, a guideline should be an ordered list of items with some general metadata (ie. version, name, etc.).

Items can be:
  * Sections (with a heading, to increase readability)
  * Questions with a set of allowed answers (ie. Yes/No)
    * These answers should allow to trigger subsections (ie. perform quantitative analysis - yes > show reporting of quant data section)
     * Such subsections could be stored as child elements of the question object
     * Some answers should also be able to trigger a text element to be required (for example "Used FDR filtering" > "No" > Text field shown "Why???")
   * Free text answers (specified as single line or text field)
   * Numeric answers with range

Items should be marked as:
  * required
  * belonging to a level of compliance (ie. "bronze", "silver" etc.)

**Comment by veitveit** [comment]
Some items will require using controlled vocabularies
